---
title: "Tarea 3 Algoritmos e IA"
author: "Lucia Martinez, Carlos Garcia y Estefani Casallas"
date: "2025-01-19"
output: html_document
---

# Actividad Grupal:
Análisis de un conjunto de datos de origen biológico mediante técnicas de machine learning supervisadas y no supervisadas


```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, # Hace que el código se muestre en el html
                      message = FALSE, # Para no mostrar los mensajes
                      warning = FALSE, # Para no mostrar los avisos
                      fig.align = 'center' # Para que las figuras salgan alineadas en el html
)

```

```{r Preparación del entorno de trabajo (instalación y carga de paquetes), include=TRUE}

#install.packages()
library()

```

## Depurado del conjunto de datos
En primer lugar cargaremos los datos brutos de partida 

```{r cargar_datos}
rm(list=ls())
path<- "C:/Users/debot/Desktop/datos"
setwd(path)

# Carga de datos 
classes <- read.csv ("C:/Users/debot/Desktop/datos/classes.csv", sep = ";", header = FALSE)
gene_expression<- read.csv("C:/Users/debot/Desktop/datos/gene_expression.csv", sep = ";", header = FALSE)
column_names<- read.csv("C:/Users/debot/Desktop/datos/column_names.txt", sep = ";", header = FALSE)

# Creación de un df aglomerando los archivos cargados
data <- gene_expression
colnames(data)<-column_names[,1]
row.names(data)<-classes[,1]
data<- cbind(data,clases = classes[,2]) # añadimos la columna clases


    #---> yo eliminaria estas dos lineas
# (data) # Compruebo que las dimensiones del df son, para las columnas, una unidad mayor que en el df "gene_expression"
# table(data[,501]) # Compruebo el contenido de la nueva columna
      
# Imputación de los NA
anyNA(data) # No hay valores missing en el df
#na.omit(data) # En caso de haberlos, esta función elimina las filas que tengan un NA
#dim (data) # Para saber si se han eliminado filas usaríamos dim()


# Depurado de columnas con valores igual a 0
sumas<- colSums(data[1:500], na.rm = FALSE, dims = 1 ) # Suma de los datos por columnas
columnascero <- names(sumas[sumas==0]) # Extrae los nombres de las columnas cuya suma total de valores es igual a 0
data <- data[, !names(data) %in% columnascero] #  Eliminación del df de las columnas con suma igual a 0 

# Se muestran los columnas (genes) que se han excluido del df
print(paste("Los genes eliminados son: ", paste(columnascero[1:3], collapse = ", ")))

data[] <- lapply(data, function(x) if(is.character(x)) factor(x) else x)#transformamos las variables categóricas en factores
data_num <- data[, sapply(data, is.numeric)]
table(sapply(data_num, class))
sc_data_num <- scale(data_num)
sc_data_num_df <- as.data.frame(sc_data_num) # Conversión de la matriz a un data frame

# añadimos la columna clases al "sc_data_num_df"
sc_data_num_df$clases<-cbind(data$clases)

# Guardado de datos
write.csv(data, "df procesado.csv", row.names = FALSE)
write.csv(sc_data_num_df, "df val escalados.csv", row.names = FALSE)
```
